src/CodeEditor.tsx, src/__stories__/CodeEditor.tsx, src/utils/highlightCode.ts
[SL-715](https://stoplightio.atlassian.net/browse/SL-715)
**Notes for reviewer**
- `prismjs` loads only a handful of syntax highlighters by default (marked as `defaultLanguages` in the code)
- slate-editor claims to support all other languages but since prismjs does not load them be default, switching to one of them fails with an exception:
- my code lists and groups all supported languages but comments them out because they won't load out of the box. we will have to figure out a proper babel configuration to load them (https://github.com/mAAdhaTTah/babel-plugin-prismjs).
=> fix(code-editor): fail gracefully when cannot highlight code SL-715

src/Checkbox.tsx, src/Input.tsx, src/Select.tsx, src/Textarea.tsx, src/__stories__/Forms/Checkbox.tsx, src/__stories__/Forms/Input.tsx, src/__stories__/Forms/Select.tsx, src/__stories__/Forms/Textarea.tsx, src/__stories__/Views/Components.tsx, src/theme/dark.ts, src/theme/light.ts, src/theme/types.ts
Add an optional `invalid` prop to `Checkbox`, `Input`, `Select`, and `Textarea` that activates the invalid style variant.
Normal, Light:
Invalid, Light:
Normal, Dark:
Invalid, Dark:
=> feat: add invalid variants for Checkbox, Input, Select, and Textarea [SL-1788]

src/theme/dark.ts, src/theme/light.ts
I left transparency in where it made sense: shadows, overlay, scrollbars.
=> fix: remove unnecessary transparency

src/ContextMenu.tsx, src/__tests__/ContextMenu.spec.tsx
We can't return null from `ContextMenuView` because it has internal state that is used to render when triggered by `ContextMenuTrigger`. Instead of returning null when we don't have any menu items, we instead return a placeholder.
=> fix: context menu needs to render a placeholder

package.json, src/BlockQuote.tsx, src/Box.tsx, src/Break.tsx, src/Button.tsx, src/Checkbox.tsx, src/Code/Editor.tsx, src/Dialog.tsx, src/Flex.tsx, src/Heading.tsx, src/Icon.tsx, src/Image.tsx, src/Input.tsx, src/Link.tsx, src/List.tsx, src/Menu.tsx, src/Overlay.tsx, src/Popup/PopupContent.tsx, src/Popup/types.ts, src/ScrollBox.tsx, src/ScrollList.tsx, src/Table.tsx, src/Text.tsx, src/Textarea.tsx, src/Toaster/Toast.tsx, src/Toaster/index.tsx, src/Toggle.tsx, src/Tooltip.tsx, src/__stories__/Code/Editor.tsx, yarn.lock
Confirmed typings working again in Studio. In order to get this working I had to basically clobber type checking on the `ref` property (for example won't yell at you if you pass a div ref to a component expecting a span ref). This is imho not super critical, and getting the general typings working is far more important.
Fixing the typings also caught a few issues which are fixed in this PR.
=> fix: forwardRef typings support [SL-1906]

README.md, docs/components.md, docs/theme-base.md, docs/theme.md
* Fix some imprecise parts (we're not using styled-components, for example)
* Remove the component list (it was outdated and not providing any useful help)
* Use embedded markdown links where possible
* Add a FAQ about what are the "strange" properties (this is what would have helped me)
* Put the migration guide on bottom
* Put the Creating a Component section on the bottom since it's not the default use case
=> docs: revisit and clarify some parts SL-1879

src/Icon.tsx, src/__stories__/Utilities/Icon.tsx
Repos checked that use ui-kit
- studio https://github.com/stoplightio/studio/pull/162
- json-schema-viewer https://github.com/stoplightio/json-schema-viewer/pull/8
- json-schema-editor https://github.com/stoplightio/json-schema-editor/pull/11
- tree-list https://github.com/stoplightio/tree-list/pull/51
- formtron (icon size not used)
- monaco (icon size not used)
- markdown-viewer (icon size not used)
- platform (icon size not used)
=> fix(icon): drop icon size prop

src/Box.tsx, src/Button.tsx, src/__stories__/Misc/Dialog.tsx, src/__stories__/Misc/Popup.tsx, src/__stories__/Views/Layout.tsx, src/__tests__/Dialog.spec.tsx, src/__tests__/Flex.spec.tsx, src/__tests__/Image.spec.tsx, src/styles.ts, src/theme/configuration.ts, src/theme/index.tsx
With this update we will need to updated the spacing values in all relevant repos
For reference old scale:
```
const spaceScale = {
0: 0px,
1: 4px,
2: 8px,
3: 16px,
4: 32px,
5: 64px,
6: 128px,
};
```
new scale 
```
const space = {
0: '0px',
// increase by 2*0 = 1
1: '1px',
2: '2px',
3: '3px',
4: '4px',
5: '5px',
// increase by 2*1 = 2
6: '6px',
7: '8px',
8: '10px',
9: '12px',
10: '14px',
// increase by 2*2 = 4
11: '18px',
12: '22px',
13: '26px',
14: '30px',
15: '34px',
// increase by 2*3 = 6
16: '40px',
17: '46px',
18: '52px',
19: '60px',
20: '66px',
// increase by 2*4 = 8
21: '78px',
22: '86px',
23: '94px',
24: '102px',
25: '110px',
};
```
pointers
```
old => new
7 => 25
6 => 25
5 => 20
4 => 15
3 => 11
2 => 7
1 => 4
0 => 0
```
=> Sl 1904/spacing values

src/Select.tsx
It turned out `isFocused` doesn't reflect `hover` state in all cases.
I faced an issue here https://github.com/stoplightio/studio/pull/174
=> fix: select :hover issue

src/_hooks/useValidateSchema.ts
~Not sure why exactly this was causing the problem but lets just remove it for now~
Since the `validateOpts` object is being created on each render, it invalidates the useEffect on each render which causes it to get into an infinite loop
=> fix: validateOpts causes maximum depth

src/ScrollList/index.tsx, src/__stories__/ScrollList/index.tsx
The property might be useful if you want to add extra padding at the end of the list to highlight the fact you can scroll the list down. Didn't make it a default, as there are cases this might not be the desired behavior.
=> feat(fixed-size-list): visual offset

src/__stories__/Code/CodeEditor.tsx, src/__stories__/Code/CodeViewer.tsx, src/styles/components/Code/_base.scss
Don't add any before/after screenshots, as there is really nothing to compare.
At the moment, everything is displayed as it was a plain text.
=> fix(code-viewer): syntax highlighting

src/ScrollContainer/index.tsx, src/ScrollList/index.tsx
Fixed sized list is passing reference to custom scrollbar container which needs to be forwarded further to scrollbar component. 
When it was attached to div container manipulating list with `instanceRef` was buggy.
=> fix: custom scrollbar container ref forwarding

src/styles/tailwind/tailwind.config.js
- we have positive pixel margin so it make sense to have a negative one.
- useful for overriding a border.
https://github.com/stoplightio/ui-kit/blob/986d1eff587afedc8220f08843e32c7f37bd6bce/src/styles/tailwind/tailwind.config.js#L50
=> fix: add negative px margin

src/FormButton/index.tsx, src/FormInput/index.tsx, src/_hooks/useValidateSchema.ts
- add support for passing props to the validations tooltip
- add support for passing in errors directly to FormInput
- update useValidateSchema to always return an array
- only render errors in a list if there's more than one
=> feat: add validation tooltip props

src/CodeEditor/index.tsx, src/CodeEditor/utils/highlightCode.ts, src/CodeViewer/__tests__/Viewer.spec.tsx, src/CodeViewer/index.tsx, src/__stories__/Code/CodeEditor.tsx, src/styles/components/Code/_base.scss
- removes left padding when line numbers isn't enabled
- adds line numbers even when the textarea is empty
- adds highlighting to inline code
- adds memoization to prism highlight
=> fix: code editor and viewer line numbers

src/CodeEditor/utils/highlightCode.ts
Add `OCaml` highlighting styles for `CodeEditor` and `CodeViewer`
=> fix: add ocaml language support

src/styles/components/SimpleTabs/_base.scss
=> fix(styles): fix dark mode for SimpleTabs

.circleci/config.yml, src/__stories__/FormInput/index.tsx, src/__stories__/index.ts, src/_hooks/useValidateSchema.ts
I added async yup schema support for `FormInput`.
This is something that can simplify our lives many times when implementing async validations for hubs.
I additionally added a story to test and demonstrate the behavior, and improved typings a little.
=> feat: async validation support for FormInput

src/__stories__/FormButton/index.tsx, src/__stories__/index.ts, src/_hooks/useValidateSchema.ts
Currently `FormButton` does not work with object `data` and `schema`, which makes it quite useless.
The problem is that for some reason if we pass a configuration object to `yup`, even `undefined` properties of said object override defaults. (They act as false.) 
This means we were effectively always passing `abortEarly: false, recursive: false`. I fixed the default for `abortEarly`, and I removed the option for `recursive` as neither did we ever use it, nor can I think of a situation where it can be useful. This is an internal hook, so the change is not breaking.
I also added a story to highlight the problem, that takes up the majority of lines added in this PR.
=> fix: object validation for `useValidateSchema` & story for FormButton

package.json, src/FormButton/index.tsx, src/FormInput/index.tsx, src/__stories__/FormInput/index.tsx, src/_hooks/useValidateSchema.ts, yarn.lock
This is based on @lottamus's PR feedback for https://github.com/stoplightio/platform-internal/pull/1748
Debounces the yup schema validation `FormInput` and `FormButton` have.
These are opinionated, let me know if you want to change anything.
- A valid input still does not show any icon.
- The invalid icon was changed to include an exclamation mark in the middle to be more consistent with the _stale/validating_ icon (see below). 
- If there _was_ an error during the latest validation, but the input changed since (_stale/validating_), this icon is shown:
- If the last state was _correct_ but the input changed since, we don't show anything. A flashing icon would look bad IMO, so unless we add an icon for the valid state, this is probably nicer behavior.
I also fixed the vertical alignment of …
=> feat: debounced validation for `FormInput` / `FormButton`

src/styles/components/Code/_base.scss
=> fix: dark theme CodeEditor

src/ScrollContainer/index.tsx
Fixes stoplightio/platform-internal#457
In my experience (I have encountered such situation in an earlier project) the flickering occurs because of some rounding errors. The exact numbers are probably off, but here is roughly what happens:
1. There's about a let's say *999.5px* wide area remaining for the `AutoSizer` to fill.
2. The `AutoSizer` rounds this up, reports a width of *1000px*.
3. The `AutoSizer`'s content is stretched out to *1000px*. 
4. The browser recognizes that those 1000 pixels aren't going to exactly fit (there's only *999.5px* of space), so it introduces a scrollbar.
5. Introducing the scrollbar means there's now less space for the `AutoSizer`, which then recalculates it's size.
6. This time it happens to round in the "correct" dimension, so the content is resized to …
=> Fix: scrollbar flicker

package.json, yarn.lock
Follow up of https://github.com/stoplightio/yaml/pull/45 and https://github.com/stoplightio/yaml/issues/36 for `ui-kit`
=> chore: explicit `tslib` dependency

src/TableOfContents/index.tsx
Related to stoplightio/platform-internal#2527
While the PR for that issue (stoplightio/platform-internal#2537) was in review, a new prop was added to the TableOfContents component in `ninja`. stoplightio/platform-internal#2332
In this PR I migrate that prop too.
Two changes I made:
- I named the prop `data-test` instead of `dataTest` so it is consistent with the native `data-test` prop on HTML elements.
- I added a short documentation sentence.
When I pull this into stoplightio/platform-internal#2537 I'll update the e2e test to reflect the prop name change.
=> feat(table-of-contents): add data-test attribute

src/TableOfContents/index.tsx
hint: It's still a mess
This is relevant because of https://github.com/stoplightio/platform-internal/issues/2527
That error is a result of us using an any-typed `rowRenderer`:
```ts
const rowRenderer = React.useCallback<any>(
```
https://github.com/stoplightio/elements/blob/beta/src/components/TableOfContents/index.tsx#L19
It turns out it is incredibly hard to correctly get the type of the callback, and having that `getProps: typeof computeTableOfContentsItemProps` is also prone to accidental breaking changes.
I pulled out the type of the rowRenderer to an explicitly defined type, and inlined the `typeof computeTableOfContentsItemProps` definition to make it a stable API.
IMO this renderer signature is still a mess, but I intended not to change it in this PR, just type it more explicitly.
=> feat: properly type RowRenderer

src/TableOfContents/index.tsx, src/__fixtures__/table-of-contents/studio.ts
The `TableOfContents` component will auto expand and scroll to make sure it shows items that are `isActive: true`, by default.
Will be used to resolve stoplightio/platform-internal#2308
The expand part works, scroll functionality to be done.
=> feat(Table of Contents): auto expand to show active items

src/styles/components/Code/_base.scss
This one has been caught by Marc.
before:
after:
=> fix(code-viewer): reduce initial layout shift

src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx, src/styles/components/Code/_base.scss
Instead of pre-defined value, let's actually adjust the width according to the number of digits
Before:
After:
=> feat(code-viewer): align line numbers to the right

src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx, src/CodeViewer/components/BlockCodeViewer/SingleCodeBlock.tsx, src/CodeViewer/components/BlockCodeViewer/consts.ts
This could have been done as a part of https://github.com/stoplightio/ui-kit/pull/179, but 179 is a no-brainer, while this one might potentially break something (it shouldn't, though).
It also improves support for initial scrollTop scenario.
=> feat(code-viewer): scroll overscan

src/TableOfContents/index.tsx
closes #181
I believe that only ninja uses it, and it makes more sense to handle this filtering outside of the table of contents component.
Here's the platform PR that updates ninja to no longer use these props: https://github.com/stoplightio/platform-internal/pull/3881.
=> fix(removal): remove filter and select from table of contents

src/TableOfContents/index.tsx
Addresses https://github.com/stoplightio/platform-internal/issues/3949
Adds optional `isExternalLink` property to ToC link items.
This could be done in Elements though there we'd have to handle both toc tree and branch nodes computing functions.
=> feat: toc external link

src/CodeViewer/components/BlockCodeViewer/SingleCodeBlock.tsx, src/styles/components/Code/_base.scss
Followup to #192 and stoplightio/platform-internal#4086
Animates the transition from plain text view to highlighted view.
When first rendering the CodeViewer it does not perform syntax highlighting.
To optimize performance highlighting happens after rendering in a `useEffect` hook. This causes a flicker when the coloring is finally applied to the text. This is especially noticable when the initial render is performed server-side.
This fix smoothens out the process using a short (0.3s) animation to introduce the color.
The library CodeEditor is using is probably missing some keys, which makes every token `div` remounted on change (which happens quite often in an editor). This causes repeated animations.
Fixed that ugly `as any` cast.
Check out the codeviewer storybooks.
=> feat(code-viewer): animated transition from plain to highlighted

package.json, yarn.lock
To remove version conflict and resolution in https://github.com/stoplightio/elements/pull/607
Only types changed.
=> feat: bump fontawesome types to latest version

.storybook/preview-head.html, src/TableOfContents/index.tsx, src/__fixtures__/table-of-contents/tree.ts, src/__stories__/TableOfContents/index.tsx
Needed by https://github.com/stoplightio/elements/issues/639
Changes:
- fixes collapsing all descendant children nodes when toggling parent (nested nodes remained open - I've added a simple story for that)
- adds toc item icons positioning (we need to have them on both sides)
- allows using text labels instead of icons (i.e. for oas operation labels)
- splits group items containing `to` property so they can have both actions handled
~~Note: note sure if we should use paid FA icons here (as in original issue). IIRC elements were supposed to use free version which leaves platform without a choice.~~
=> feat: Display endpoint method and icons for schema and API

src/TableOfContents/index.tsx, src/__fixtures__/table-of-contents/tree.ts
Needed by https://github.com/stoplightio/elements/pull/722
Adds support for initially expanded ToC items.
=> feat: toc start expanded
