stoplightio/ui-kit

- src/Select.tsx
- src/__stories__/Forms/Select.tsx
- src/__stories__/Forms/index.ts
Apparently, a story for Select component was missing.
Re-added it + exported interfaces for consistency.
> chore(select): Select story

- src/Select.tsx
- src/__stories__/Forms/Select.tsx
> feat: introduce async select

- __mocks__/react-contextmenu.ts
- setupTests.ts
- src/ContextMenu.tsx
- src/__tests__/ContextMenu.spec.tsx
ContextMenuTrigger re-export + IContextMenu export + MenuView export + use of JSX.
> chore: re-export trigger + minor adjustments

- src/Checkbox.tsx
- src/Toggle.tsx
- Adds optional `checked` property to Checkbox and Toggle interfaces
> fix: add "checked" to checkbox/toggle interface

- src/index.ts
> fix: export tabs so I can use them! :trollface:

- src/Select.tsx
- src/theme/dark.ts
- src/theme/light.ts
- src/theme/types.ts
Before / After:
Before / After:
> fix: improve "dark" theme color consistency

- src/BlockQuote.tsx
- src/Link.tsx
- src/__stories__/Typography/Link.tsx
- src/__tests__/BlockQuote.spec.tsx
- src/__tests__/Link.spec.tsx
- src/theme/dark.ts
- src/theme/light.ts
- src/theme/types.ts
> [SL-1773] styles for Link & BlockQuote

- src/BlockQuote.tsx
- src/Break.tsx
- src/Button.tsx
- src/Code/Editor.tsx
- src/Code/Viewer.tsx
- src/Dialog.tsx
- src/Heading.tsx
- src/Icon.tsx
- src/Image.tsx
- src/Input.tsx
- src/Link.tsx
- src/List.tsx
- src/ScrollBox.tsx
- src/ScrollList.tsx
- src/Table.tsx
- src/Tabs/Tab.tsx
- src/Tabs/index.tsx
- src/Text.tsx
- src/Textarea.tsx
- src/Toggle.tsx
- src/__stories__/Misc/Tabs.tsx
- src/__tests__/BlockQuote.spec.tsx
- src/__tests__/Dialog.spec.tsx
- src/__tests__/Image.spec.tsx
- src/__tests__/Input.spec.tsx
- src/__tests__/Link.spec.tsx
Fixes up most of the components to correctly pass `css` through.
> fix: consistently pass css through [SL-1827]

- src/BlockQuote.tsx
- src/Code/Viewer.tsx
- src/Code/styles.ts
- src/Link.tsx
- src/Table.tsx
- src/Tabs/Tab.tsx
- src/Tabs/TabPanel.tsx
- src/__tests__/Link.spec.tsx
- src/__tests__/Table.spec.tsx
- src/theme/dark.ts
- src/theme/light.ts
- src/theme/types.ts
Depends on #70 
This PR makes many minor modifications to various styles. It is required for https://github.com/stoplightio/markdown-viewer/pull/2.
> fix: ui tweaks

- README.md
- src/Badge.tsx
- src/__stories__/Utilities/Badge.tsx
- src/__stories__/Utilities/index.ts
- src/__tests__/Badge.spec.tsx
- src/index.ts
- src/theme/dark.ts
- src/theme/light.ts
- src/theme/types.ts
Issue: https://stoplightio.atlassian.net/browse/SL-1762
> feat: SL-1762 Badge element

- src/index.ts
> fix: export Tooltip from root

- src/Badge.tsx
- src/__stories__/Utilities/Badge.tsx
- src/__tests__/Badge.spec.tsx
- yarn.lock
Added dot variant to Badge component
> feat: added dot style to badge

- src/AutoSizer.tsx
- src/ScrollList.tsx
- src/__stories__/Data/ScrollList.tsx
- yarn.lock
https://github.com/stoplightio/tree-list/pull/47
> feat: forwardRefs ScrollList [SL-1939]

- src/Toast/ToastContent.tsx
- src/__tests__/ToastContent.spec.tsx
removes default icons per type in toast
> fix: toast-icons

- src/Button.tsx
- src/Icon.tsx
- src/__tests__/Button.spec.tsx
- src/theme/light.ts
> refactor: tweak button

- package.json
- src/ContextMenu.tsx
- src/__stories__/Menus/ContextMenu.tsx
- src/__tests__/ContextMenu.spec.tsx
- yarn.lock
* Support for Shortcut through an additional property; it gets put at the end of the current menuItem
* Make sure the background color spans on the whole menu item
> feat: Context Menu Improvements SL-2244 SL-2245

- src/Select.tsx
As needed by https://github.com/stoplightio/json-schema-editor/pull/15
> fix: export select styles

- src/SecretInput/index.tsx
- src/__stories__/SecretInput/index.tsx
- src/__stories__/index.ts
- src/index.ts
> feat: SecretInput

- src/ScrollList/index.tsx
- src/__stories__/ScrollList/index.tsx
This reverts commit 0b4b833b10c8a848aaa6d34eda8d71a57b0b58f1.
Fraction for `maxRows` does the trick as well.
> revert: "feat(fixed-size-list): visual offset (#114)"

- src/ScrollContainer/index.tsx
- src/__stories__/ScrollContainer/index.tsx
- src/styles/tailwind/_base.scss
- src/styles/tailwind/tailwind.config.js
Related to [SL-2672](https://stoplightio.atlassian.net/browse/SL-2672)
Changes:
- showing scrollbars when hovering over scrollable area
- fixing styling that were shadowed by default element styles
- styling consistent with vscode scrollbars
> feat: scrollbar container hover

- src/__stories__/Toaster/index.tsx
- src/__stories__/index.ts
I needed to mock up some screenshots of the toast mechanism.
> chore: add toaster story

- src/CodeEditor/utils/highlightCode.ts
* Add additional highlighting styles for `CodeEditor` and `CodeViewer`
> fix: update highlightCode styles

- src/TableOfContents/index.tsx
- src/TableOfContents/types.ts
- src/__fixtures__/table-of-contents/studio.ts
Related Issue: https://github.com/stoplightio/platform-internal/issues/338
> feat: add support for meta in TableOfContents item row

- tsconfig.build.json
- tsconfig.json
Essentially the replica of https://github.com/stoplightio/elements/pull/339 for `ui-kit`.
> Fix: use ES modules in the output

- tsconfig.build.json
- tsconfig.json
See https://github.com/stoplightio/elements/pull/351
> fix: revert ES module output (#149)

- package.json
- src/styles/tailwind/_base.scss
- yarn.lock
> feat: upgrade to Tailwind 1.3

- src/ScrollContainer/index.tsx
- src/ScrollList/index.tsx
- yarn.lock
Cherry-picks https://github.com/stoplightio/ui-kit/commit/af5d5624ba8577572e1fec0c096365eb607399f8 and https://github.com/stoplightio/ui-kit/commit/16be7a291180615027871630bbd151cd46f978d2
Before:
After:
> feat(scroll-container): modify scrollbarWidth

- src/TableOfContents/index.tsx
- src/styles/components/TableOfContents/_base.scss
I tried to move the TableOfContents related diffs from https://github.com/stoplightio/platform-internal/pull/2425 to here.
Rationale is that TOC is being moved here, we are going to replace the one in `platform` with this one. We should not lose features when we do so. https://github.com/stoplightio/platform-internal/issues/2219
> feat: Table of Contents update

- src/styles/components/Code/_base.scss
> fix(code-viewer): restore previous css

- src/TableOfContents/index.tsx
- src/__stories__/TableOfContents/index.tsx
Fixes the scroll part of stoplightio/platform-internal#2308
> feat(toc): scroll the active item into view on mount

- package.json
- src/TableOfContents/index.tsx
- src/styles/components/TableOfContents/_base.scss
- yarn.lock
- drop the px a bit on table of contents
- bump blueprint deps and a couple of other patch updates
> fix: update TOC spacing, bump blueprint deps

- src/CodeEditor/index.tsx
- src/styles/components/Code/_base.scss
> feat(code-editor): support intent prop

- src/CodeEditor/index.tsx
- src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx
- src/CodeViewer/components/InlineCodeViewer.tsx
- src/classes.ts
- src/styles/components/Code/_base.scss
Fixes https://github.com/stoplightio/platform-internal/pull/3852#issuecomment-669308594
> fix(code-editor): line numbers are off

- src/CodeViewer/__tests__/Viewer.spec.tsx
- src/CodeViewer/components/BlockCodeViewer/SingleCodeBlock.tsx
- src/CodeViewer/utils/__tests__/__snapshots__/astToReact.spec.ts.snap
- src/CodeViewer/utils/__tests__/__snapshots__/lineNumberify.spec.ts.snap
- src/CodeViewer/utils/__tests__/lineNumberify.spec.ts
- src/CodeViewer/utils/astToReact.ts
- src/CodeViewer/utils/lineNumberify.ts
- src/CodeViewer/utils/parseCode.ts
Fixes https://github.com/stoplightio/platform-internal/pull/3852#issuecomment-669169794
> fix(code-viewer): line numbers are incorrect in certain cases

- src/TableOfContents/index.tsx
- src/__stories__/TableOfContents/index.tsx
This PR adds a prop to the `TableOfContents` that will be passed down to the `rowComponent`.
The thing is type-safe (apart from that error which I couldn't find the cause of and *ts-ignore*d), it only lets you pass `rowComponentExtraProps` if the specified `rowComponent` requires them.
Check out the new stories for demonstration.
This allows us to avoid the very error prone action of creating components inside other components using `useCallback`.
As an example check out `ninja` on the `feat/custom-toc` branch: https://github.com/stoplightio/platform-internal/blob/feat/custom-toc/packages/ninja/src/screens/Workspace/Sidebar/Project.tsx#L323-L358
Currently there is no nice way to achieve that behavior, because the component relies on `itemPath`. But this is not how `rowComponent` is …
> feat(table-of-contents): rowComponentExtraProps

- setupTests.ts
- src/CodeViewer/__tests__/Viewer.spec.tsx
- src/CodeViewer/components/BlockCodeViewer/BlockCodeViewer.tsx
- src/CodeViewer/components/BlockCodeViewer/ObservableSet.ts
- src/CodeViewer/components/BlockCodeViewer/SingleCodeBlock.tsx
- src/CodeViewer/components/BlockCodeViewer/hooks/useSlicedBlocks.ts
- src/styles/components/Code/_base.scss
Fixes https://github.com/stoplightio/platform-internal/pull/3901#issuecomment-671279905
I realllly hope this is the last PR :laughing:
> fix(code-viewer): get rid of trailing lines

- src/TableOfContents/index.tsx
Fixes https://github.com/stoplightio/platform-internal/pull/3901#issuecomment-675145014
> fix(table-of-contents): typing issue
